[package]
name = "zombie_simulator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
eyre = "0.6.5"
ggez = "0.6.0"

[dependencies.jecs]
version = "0.1.0"
path = "../jecs"