name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Fix alsa-sys
      run: sudo apt install libasound2-dev
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
    - uses: katyo/publish-crates@v1
      with:
        path: "./jecs"
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
